---

argument_specs:
  main:
    short_description: Manages hardware related settings.
    options:
      hardware_packages:
        description:
          - List of hardware related packages to install.
        type: list
        elements: str
        required: no
        default:
          - intel-ucode
          - sof-firmware
      hardware_service_activation:
        description:
          - List of hardware related services to activate.
        type: list
        elements: str
        required: no
        default:
          - fstrim.timer
