---

- name: configure wayfire pacman repositories
  ansible.builtin.include_tasks:
    file: repositories.yml
  loop: '{{ wayfire_repositories }}'
  loop_control:
    label: '{{ repository.name }}'
    loop_var: repository
  when: wayfire_repositories is defined

- name: flush handlers to ensure pacman database is refreshed
  ansible.builtin.meta: flush_handlers

- name: install wayfire packages
  ansible.builtin.package:
    name: '{{ wayfire_packages }}'
    state: present

- name: create directory for greetd integration config
  ansible.builtin.file:
    path: /etc/greetd
    owner: root
    group: root
    mode: 0755
    state: directory
  when: (wayfire_greetd_config is defined) and
        (wayfire_greetd_config | length > 0)

- name: configure greetd integration config
  ansible.builtin.template:
    src: etc/greetd/wayfire.ini.j2
    dest: /etc/greetd/wayfire.ini
    owner: root
    group: root
    mode: 0644
  when: (wayfire_greetd_config is defined) and
        (wayfire_greetd_config | length > 0)

- name: deploy wayfire-run wrapper script
  ansible.builtin.template:
    src: usr/local/bin/wayfire-run.j2
    dest: /usr/local/bin/wayfire-run
    owner: root
    group: root
    mode: 0755
  when: (wayfire_run_wrapper is defined) and
        (wayfire_run_wrapper | length > 0)
