---

- name: Check if gpg key is trusted for pacman repository {{ repository.name }}
  ansible.builtin.command:
    pacman-key --finger {{ repository.key_id }}
  register: wayfire_register_key
  changed_when: no
  failed_when: no

- name: Download gpg key for pacman repository {{ repository.name }}
  ansible.builtin.get_url:
    url: '{{ repository.key }}'
    dest: /tmp/{{ repository.key_id }}.asc
    owner: root
    group: root
    mode: 0644
  when: wayfire_register_key.rc == 1

- name: Add gpg key for pacman repository {{ repository.name }}
  ansible.builtin.command:
    pacman-key --add /tmp/{{ repository.key_id }}.asc
  when: wayfire_register_key.rc == 1

- name: Trust gpg key for pacman repository {{ repository.name }}
  ansible.builtin.command:
    pacman-key --lsign-key {{ repository.key_id }}
  when: wayfire_register_key.rc == 1

- name: Add entry to pacman.conf for {{ repository.name }}
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [{{ repository.name }}]
      Server = {{ repository.server }}
    owner: root
    group: root
    mode: 0644
    state: present
  notify: Refresh pacman database
