---

# List of additional packages to install
wayfire_dependencies:
  - polkit

# Optional greetd integration config to deploy
wayfire_greetd_config: ''

# List of wayfire related packages to install including their version
wayfire_packages:
  - name: wf-config
    version: 0.7.1-3
    url: 'https://github.com/karras/aur-package-builds/releases/download/v1.0.1'
    suffix: -x86_64.pkg.tar.zst
  - name: wayfire
    version: 0.7.2-1
    url: 'https://github.com/karras/aur-package-builds/releases/download/v1.0.1'
    suffix: -x86_64.pkg.tar.zst
