---

- name: Converge
  hosts: all
  gather_facts: true

  tasks:
    - name: Include role firewalld
      ansible.builtin.include_role:
        name: karras.linux_client.firewalld
      vars:
        firewalld_default_zone: drop
        firewalld_services:
          - ssh
