---

- name: Verify
  hosts: all
  gather_facts: no

  tasks:
  - name: load role defaults
    ansible.builtin.include_vars:
      file: ../../defaults/main.yml

  - name: test selected cis sections
    ansible.builtin.include_tasks:
      file: 'tests/{{ item }}.yml'
    loop: '{{ cis_baseline_sections }}'
    when: cis_baseline_sections is defined
