---

namespace: karras
name: linux_client
version: 1.0.0
readme: README.md
authors:
  - Michael Hofer <@karras>
description: A collection of roles to manage Linux-based development clients.
license_file: LICENSE
tags:
  - linux
  - client
  - workstation
  - laptop
  - desktop
  - archlinux
dependencies: {}
repository: https://github.com/karras/ansible-collection-linux_client
documentation: https://github.com/karras/ansible-collection-linux_client
homepage: https://github.com/karras/ansible-collection-linux_client
issues: https://github.com/karras/ansible-collection-linux_client/issues
build_ignore: []
