---

# List of locales to activate
os_baseline_locales:
  - 'en_US.UTF-8 UTF-8'
  - 'en_US ISO-8859-1'

# Configuration of the system-wide locales
os_baseline_locales_config:
  lang: en_US.UTF-8
  language: en_US.UTF-8
  lc_address: en_US.UTF-8
  lc_collate: en_US.UTF-8
  lc_ctype: en_US.UTF-8
  lc_identification: en_US.UTF-8
  lc_measurement: en_US.UTF-8
  lc_messages: en_US.UTF-8
  lc_monetary: en_US.UTF-8
  lc_name: en_US.UTF-8
  lc_numeric: en_US.UTF-8
  lc_paper: en_US.UTF-8
  lc_telephone: en_US.UTF-8
  lc_time: en_US.UTF-8

# List of mirrors to activate
os_baseline_mirrors:
  - 'https://pkg.adfinis.com/archlinux/$repo/os/$arch'

# List of baseline packages to install
os_baseline_packages:
  - base
  - dhclient
  - intel-ucode
  - linux
  - linux-firmware
  - lvm2
  - vi

# Configuration for systemd-timesyncd (see `man timesyncd.conf`)
os_baseline_timesyncd_config:
  ntp:
  fallback_ntp: '0.arch.pool.ntp.org 1.arch.pool.ntp.org 2.arch.pool.ntp.org 3.arch.pool.ntp.org'
  root_distance_max_sec: 5
  poll_interval_min_sec: 32
  poll_interval_max_sec: 2048

# Timezone to configure
os_baseline_timezone: Etc/UTC

# Whether the hardware clock is in UTC or local timezone
# Valid values are 0 ('UTC') and 1 ('local')
os_baseline_timezone_hwclock: 0
