---

argument_specs:
  main:
    short_description: Manages CIS security baseline settings for clients.
    options:
      cis_baseline_bootloader_configs:
        description:
          - List of bootloader configs for which to verify their permissions
            (1.4.1).
        type: list
        elements: str
        required: false
        default:
          - /boot/loader/loader.conf
          - /boot/loader/entries/arch.conf
      cis_baseline_bootloader_loader_config:
        description:
          - Main systemd boot loader config to disable editor (1.4.2).
        type: str
        required: false
        default: /boot/loader/loader.conf
      cis_baseline_gpg_key_packages:
        description:
          - List of gpg key packages to install (1.2.2).
        type: list
        elements: str
        required: false
        default:
          - archlinux-keyring
      cis_baseline_ignored_rules:
        description:
          - List of specific CIS rules to ignore.
        type: list
        elements: str
        required: false
        default: []
      cis_baseline_login_banner_local:
        description:
          - Content of the local login banner (1.7.1.2).
        type: str
        required: false
        default: 'Authorized uses only. All activity may be monitored and reported.'
      cis_baseline_login_banner_remote:
        description:
          - Content of the remote login banner (1.7.1.3).
        type: str
        required: false
        default: 'Authorized uses only. All activity may be monitored and reported.'
      cis_baseline_motd:
        description:
          - Content of the message of the day (1.7.1.1).
        type: str
        required: false
        default: 'Authorized uses only. All activity may be monitored and reported.'
      cis_baseline_removable_media_partitions:
        description:
          - List of removable media partitions (1.1.18 - 1.1.20).
        type: list
        elements: str
        required: false
        default:
          - /mnt/cdrom
          - /mnt/floppy
      cis_baseline_repositories:
        description:
          - List of mandatory repositories to verify (1.2.1).
        type: list
        elements: str
        required: false
        default:
          - core
          - extra
      cis_baseline_repository_siglevel:
        description:
          - List of mandatory repository signature trust levels to verify
            (1.2.2).
        type: list
        elements: str
        required: false
        default:
          - PackageRequired
          - PackageTrustedOnly
          - DatabaseOptional
          - DatabaseTrustedOnly
      cis_baseline_sections:
        description:
          - List of CIS rule sections to include.
        type: list
        elements: str
        required: false
        default:
          - 1_1_filesystem
          - 1_2_software_updates
          - 1_3_filesystem_integrity
          - 1_4_boot_settings
          - 1_5_process_hardening
          - 1_6_mandatory_access_control
          - 1_7_warning_banners
