---

argument_specs:
  main:
    short_description: Manages CIS security baseline settings for clients.
    options:
      cis_baseline_sections:
        description:
          - List of CIS rule sections to include.
        type: list
        elements: str
        required: no
        default:
          - 1.1
      cis_baseline_ignored_rules:
        description:
          - List of specific CIS rules to ignore.
        type: list
        elements: str
        required: no
        default: []
