---

argument_specs:
  main:
    short_description: Manages CIS security baseline settings for clients.
    options:
      cis_baseline_sections:
        description:
          - List of CIS rule sections to include.
        type: list
        elements: str
        required: false
        default:
          - 1_1_filesystem
          - 1_2_software_updates
      cis_baseline_gpg_key_packages:
        description:
          - List of gpg key packages to install (1.2.2).
        type: list
        elements: str
        required: false
        default:
          - archlinux-keyring
      cis_baseline_ignored_rules:
        description:
          - List of specific CIS rules to ignore.
        type: list
        elements: str
        required: false
        default: []
      cis_baseline_repositories:
        description:
          - List of mandatory repositories to verify (1.2.1).
        type: list
        elements: str
        required: false
        default:
          - core
          - extra
      cis_baseline_repository_siglevel:
        description:
          - List of mandatory repository signature trust levels to verify
            (1.2.2).
        type: list
        elements: str
        required: false
        default:
          - PackageRequired
          - PackageTrustedOnly
          - DatabaseOptional
          - DatabaseTrustedOnly
      cis_baseline_removable_media_partitions:
        description:
          - List of removable media partitions (1.1.18 - 1.1.20).
        type: list
        elements: str
        required: false
        default:
          - /mnt/cdrom
          - /mnt/floppy
