---

- name: Verify
  hosts: all
  gather_facts: no

  tasks:
  - name: check if /home/clark exists
    ansible.builtin.stat:
      path: /home/clark
    register: out
    failed_when:
      - not out.stat.exists
