---

- name: Converge
  hosts: all
  gather_facts: yes

  roles:
    - role: os_baseline
      os_baseline_timezone_hwclock: 0
      os_baseline_timezone: Europe/Busingen
      os_baseline_locales:
        - 'fr_CH.UTF-8 UTF-8'
