---

- name: Verify
  hosts: all
  gather_facts: no

  tasks:
  - name: verify if hwclock is set to utc
    ansible.builtin.command:
      timedatectl show -p LocalRTC --value
    register: this
    changed_when: no
    failed_when:
      - "'no' not in this.stdout"

  - name: verify if timezone is set to utc
    ansible.builtin.command:
      timedatectl show -p Timezone --value
    register: this
    changed_when: no
    failed_when:
      - "'UTC' not in this.stdout"

  - name: verify if en_gb locale is active
    ansible.builtin.command:
      localectl list-locales
    register: this
    changed_when: no
    failed_when:
      - "'en_GB.UTF-8' not in this.stdout"
