---

- name: Verify
  hosts: all
  gather_facts: no

  tasks:
  # Update the pacman cache as it's potentialy outdated in the container
  - name: update pacman cache
    ansible.builtin.command:
      pacman -Sy
    when: ansible_distribution == 'Archlinux'
