---

# 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
- name: 1.1.1.1 disable cramfs filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_cramfs.conf.j2
    dest: /etc/modprobe.d/cis_cramfs.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.1' in cis_baseline_ignored_rules

# 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
- name: 1.1.1.1 remove loaded cramfs filesystem module
  ansible.builtin.command:
    modprobe -r cramfs
  changed_when: no
  failed_when: no
  when: not '1.1.1.1' in cis_baseline_ignored_rules

# 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled (Scored)
- name: 1.1.1.2 disable freevxfs filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_freevxfs.conf.j2
    dest: /etc/modprobe.d/cis_freevxfs.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.2' in cis_baseline_ignored_rules

# 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled (Scored)
- name: 1.1.1.2 remove loaded freevxfs filesystem module
  ansible.builtin.command:
    modprobe -r freevxfs
  changed_when: no
  failed_when: no
  when: not '1.1.1.2' in cis_baseline_ignored_rules

# 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled (Scored)
- name: 1.1.1.3 disable jffs2 filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_jffs2.conf.j2
    dest: /etc/modprobe.d/cis_jffs2.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.3' in cis_baseline_ignored_rules

# 1.1.1.3 Ensure mounting of freevxfs filesystems is disabled (Scored)
- name: 1.1.1.3 remove loaded jffs2 filesystem module
  ansible.builtin.command:
    modprobe -r jffs2
  changed_when: no
  failed_when: no
  when: not '1.1.1.3' in cis_baseline_ignored_rules

# 1.1.1.4 Ensure mounting of hfs filesystems is disabled (Scored)
- name: 1.1.1.4 disable hfs filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_hfs.conf.j2
    dest: /etc/modprobe.d/cis_hfs.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.4' in cis_baseline_ignored_rules

# 1.1.1.4 Ensure mounting of hfs filesystems is disabled (Scored)
- name: 1.1.1.4 remove loaded hfs filesystem module
  ansible.builtin.command:
    modprobe -r hfs
  changed_when: no
  failed_when: no
  when: not '1.1.1.4' in cis_baseline_ignored_rules

# 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled (Scored)
- name: 1.1.1.5 disable hfsplus filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_hfsplus.conf.j2
    dest: /etc/modprobe.d/cis_hfsplus.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.5' in cis_baseline_ignored_rules

# 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled (Scored)
- name: 1.1.1.5 remove loaded hfsplus filesystem module
  ansible.builtin.command:
    modprobe -r hfsplus
  changed_when: no
  failed_when: no
  when: not '1.1.1.5' in cis_baseline_ignored_rules

# 1.1.1.6 Ensure mounting of squashfs filesystems is disabled (Scored)
- name: 1.1.1.6 disable squashfs filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_squashfs.conf.j2
    dest: /etc/modprobe.d/cis_squashfs.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.6' in cis_baseline_ignored_rules

# 1.1.1.6 Ensure mounting of squashfs filesystems is disabled (Scored)
- name: 1.1.1.6 remove loaded squashfs filesystem module
  ansible.builtin.command:
    modprobe -r squashfs
  changed_when: no
  failed_when: no
  when: not '1.1.1.6' in cis_baseline_ignored_rules

# 1.1.1.7 Ensure mounting of udf filesystems is disabled (Scored)
- name: 1.1.1.7 disable udf filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_udf.conf.j2
    dest: /etc/modprobe.d/cis_udf.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.7' in cis_baseline_ignored_rules

# 1.1.1.7 Ensure mounting of udf filesystems is disabled (Scored)
- name: 1.1.1.7 remove loaded udf filesystem module
  ansible.builtin.command:
    modprobe -r udf
  changed_when: no
  failed_when: no
  when: not '1.1.1.7' in cis_baseline_ignored_rules

# 1.1.1.8 Ensure mounting of vfat filesystems is disabled (Scored)
- name: 1.1.1.8 disable vfat filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_vfat.conf.j2
    dest: /etc/modprobe.d/cis_vfat.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.8' in cis_baseline_ignored_rules

# 1.1.1.8 Ensure mounting of vfat filesystems is disabled (Scored)
- name: 1.1.1.8 remove loaded vfat filesystem module
  ansible.builtin.command:
    modprobe -r vfat
  changed_when: no
  failed_when: no
  when: not '1.1.1.8' in cis_baseline_ignored_rules

# 1.1.2 Ensure /tmp is configured (Scored)
# Service related tasks do not work well in molecule idempotence tests
- name: 1.1.2 enable tmp.mount service
  ansible.builtin.service:
    name: tmp.mount
    enabled: yes
    state: started
  tags:
    - molecule-idempotence-notest
  when: not '1.1.2' in cis_baseline_ignored_rules

# 1.1.3 Ensure nodev option set on /tmp partition (Scored)
- name: 1.1.3 create systemd override directory for tmp.mount
  ansible.builtin.file:
    path: /etc/systemd/system/tmp.mount.d
    owner: root
    group: root
    mode: 0755
    state: directory
  notify: system reboot
  when: not '1.1.3' in cis_baseline_ignored_rules

# 1.1.3 Ensure nodev option set on /tmp partition (Scored)
- name: 1.1.3 enable nodev option for /tmp mount point
  ansible.builtin.template:
    src: etc/systemd/system/tmp.mount.d/cis_override.conf.j2
    dest: /etc/systemd/system/tmp.mount.d/cis_override.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.3' in cis_baseline_ignored_rules
  notify: system reboot

# 1.1.4 Ensure nosuid option set on /tmp partition (Scored)
- name: 1.1.4 create systemd override directory for tmp.mount
  ansible.builtin.file:
    path: /etc/systemd/system/tmp.mount.d
    owner: root
    group: root
    mode: 0755
    state: directory
  when: not '1.1.4' in cis_baseline_ignored_rules

# 1.1.4 Ensure nosuid option set on /tmp partition (Scored)
- name: 1.1.4 enable nosuid option for /tmp mount point
  ansible.builtin.template:
    src: etc/systemd/system/tmp.mount.d/cis_override.conf.j2
    dest: /etc/systemd/system/tmp.mount.d/cis_override.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.4' in cis_baseline_ignored_rules
  notify: system reboot

# 1.1.5 Ensure noexec option set on /tmp partition (Scored)
- name: 1.1.5 create systemd override directory for tmp.mount
  ansible.builtin.file:
    path: /etc/systemd/system/tmp.mount.d
    owner: root
    group: root
    mode: 0755
    state: directory
  when: not '1.1.5' in cis_baseline_ignored_rules

# 1.1.5 Ensure noexec option set on /tmp partition (Scored)
- name: 1.1.5 enable noexec option for /tmp mount point
  ansible.builtin.template:
    src: etc/systemd/system/tmp.mount.d/cis_override.conf.j2
    dest: /etc/systemd/system/tmp.mount.d/cis_override.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.5' in cis_baseline_ignored_rules
  notify: system reboot

# 1.1.6 Ensure separate partition exists for /var (Scored)
- name: 1.1.6 test separate mount point for /var
  ansible.builtin.shell:  # noqa: command-instead-of-module
    cmd: mount | grep -E '\s/var\s'
  register: out
  changed_when: no
  failed_when:
    - out.stdout_lines | length < 1
  when: not '1.1.6' in cis_baseline_ignored_rules and
        ansible_connection not in ["container", "docker", "community.docker.docker"]

# 1.1.7 Ensure separate partition exists for /var/tmp (Scored)
- name: 1.1.7 test separate mount point for /var/tmp
  ansible.builtin.shell:  # noqa: command-instead-of-module
    cmd: mount | grep /var/tmp
  register: out
  changed_when: no
  failed_when:
    - out.stdout_lines | length < 1
  when: not '1.1.7' in cis_baseline_ignored_rules and
        ansible_connection not in ["container", "docker", "community.docker.docker"]

# 1.1.8 Ensure nodev option set on /var/tmp partition (Scored)
- name: 1.1.8 test enabled nodev option for /var/tmp mount point
  ansible.builtin.shell:  # noqa: command-instead-of-module
    cmd: mount | grep -E '\s/var/tmp\s' | grep -v nodev
  register: out
  changed_when: no
  failed_when:
    - out.stdout_lines | length > 0
  when: not '1.1.8' in cis_baseline_ignored_rules and
        ansible_connection not in ["container", "docker", "community.docker.docker"]

# 1.1.9 Ensure nosuid option set on /var/tmp partition (Scored)
- name: 1.1.9 test enabled nosuid option for /var/tmp mount point
  ansible.builtin.shell:  # noqa: command-instead-of-module
    cmd: mount | grep -E '\s/var/tmp\s' | grep -v nosuid
  register: out
  changed_when: no
  failed_when:
    - out.stdout_lines | length > 0
  when: not '1.1.9' in cis_baseline_ignored_rules and
        ansible_connection not in ["container", "docker", "community.docker.docker"]

# 1.1.10 Ensure noexec option set on /var/tmp partition (Scored)
- name: 1.1.10 test enabled noexec option for /var/tmp mount point
  ansible.builtin.shell:  # noqa: command-instead-of-module
    cmd: mount | grep -E '\s/var/tmp\s' | grep -v noexec
  register: out
  changed_when: no
  failed_when:
    - out.stdout_lines | length > 0
  when: not '1.1.10' in cis_baseline_ignored_rules and
        ansible_connection not in ["container", "docker", "community.docker.docker"]

# 1.1.11 Ensure separate partition exists for /var/log (Scored)
- name: 1.1.11 test separate mount point for /var/log
  ansible.builtin.shell:  # noqa: command-instead-of-module
    cmd: mount | grep /var/log
  register: out
  changed_when: no
  failed_when:
    - out.stdout_lines | length < 1
  when: not '1.1.11' in cis_baseline_ignored_rules and
        ansible_connection not in ["container", "docker", "community.docker.docker"]

# 1.1.12 Ensure separate partition exists for /var/log/audit (Scored)
- name: 1.1.12 test separate mount point for /var/log/audit
  ansible.builtin.shell:  # noqa: command-instead-of-module
    cmd: mount | grep /var/log/audit
  register: out
  changed_when: no
  failed_when:
    - out.stdout_lines | length < 1
  when: not '1.1.12' in cis_baseline_ignored_rules and
        ansible_connection not in ["container", "docker", "community.docker.docker"]

# 1.1.13 Ensure separate partition exists for /home (Scored)
- name: 1.1.13 test separate mount point for /home
  ansible.builtin.shell:  # noqa: command-instead-of-module
    cmd: mount | grep /home
  register: out
  changed_when: no
  failed_when:
    - out.stdout_lines | length < 1
  when: not '1.1.13' in cis_baseline_ignored_rules and
        ansible_connection not in ["container", "docker", "community.docker.docker"]

# 1.1.14 Ensure nodev option set on /home partition (Scored)
- name: 1.1.14 test enabled nodev option for /home mount point
  ansible.builtin.shell:  # noqa: command-instead-of-module
    cmd: mount | grep -E '\s/home\s' | grep -v nodev
  register: out
  changed_when: no
  failed_when:
    - out.stdout_lines | length > 0
  when: not '1.1.14' in cis_baseline_ignored_rules and
        ansible_connection not in ["container", "docker", "community.docker.docker"]

# 1.1.15 Ensure nodev option set on /dev/shm partition (Scored)
- name: 1.1.15 test enabled nodev option for /dev/shm mount point
  ansible.builtin.shell:  # noqa: command-instead-of-module
    cmd: mount | grep -E '\s/dev/shm\s' | grep -v nodev
  register: out
  changed_when: no
  failed_when:
    - out.stdout_lines | length > 0
  when: not '1.1.15' in cis_baseline_ignored_rules and
        ansible_connection not in ["container", "docker", "community.docker.docker"]
