---

# 1.7.1.1 Ensure message of the day is configured properly (Scored)
- name: 1.7.1.1 configure motd banner content
  ansible.builtin.template:
    src: etc/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
  when: not '1.7.1.1' in cis_baseline_ignored_rules

# 1.7.1.2 Ensure local login warning banner is configured properly (Scored)
- name: 1.7.1.2 configure local login banner content
  ansible.builtin.template:
    src: etc/issue.j2
    dest: /etc/issue
    owner: root
    group: root
    mode: '0644'
  when: not '1.7.1.2' in cis_baseline_ignored_rules

# 1.7.1.3 Ensure remote login warning banner is configured properly (Scored)
- name: 1.7.1.3 configure remote login banner content
  ansible.builtin.template:
    src: etc/issue.net.j2
    dest: /etc/issue.net
    owner: root
    group: root
    mode: '0644'
  when: not '1.7.1.3' in cis_baseline_ignored_rules

# 1.7.1.4 Ensure permissions on /etc/motd are configured (Scored)
- name: 1.7.1.4 ensure motd banner permissions are correct
  ansible.builtin.file:
    path: /etc/motd
    owner: root
    group: root
    mode: '0644'
  when: not '1.7.1.4' in cis_baseline_ignored_rules

# 1.7.1.5 Ensure permissions on /etc/issue are configured (Scored)
- name: 1.7.1.5 ensure local login banner permissions are correct
  ansible.builtin.file:
    path: /etc/issue
    owner: root
    group: root
    mode: '0644'
  when: not '1.7.1.5' in cis_baseline_ignored_rules

# 1.7.1.6 Ensure permissions on /etc/issue.net are configured (Scored)
- name: 1.7.1.6 ensure remote login banner permissions are correct
  ansible.builtin.file:
    path: /etc/issue.net
    owner: root
    group: root
    mode: '0644'
  when: not '1.7.1.6' in cis_baseline_ignored_rules
