---

- name: Install greetd packages
  ansible.builtin.package:
    name: '{{ greetd_packages }}'
    state: present

- name: Configure greetd main config
  ansible.builtin.template:
    src: etc/greetd/config.toml.j2
    dest: /etc/greetd/config.toml
    owner: root
    group: root
    mode: 0644
  notify: Restart greetd

- name: Configure greetd environments
  ansible.builtin.template:
    src: etc/greetd/environments.j2
    dest: /etc/greetd/environments
    owner: root
    group: root
    mode: 0644
  notify: Restart greetd

- name: Configure greetd-gtkgreet css config
  ansible.builtin.template:
    src: etc/greetd/gtkgreet.css.j2
    dest: /etc/greetd/gtkgreet.css
    owner: root
    group: root
    mode: 0644
  when: (greetd_gtkgreet_css is defined) and
        (greetd_gtkgreet_css | length > 0)
  notify: Restart greetd

# Service related tasks do not work well in molecule idempotence tests
- name: Enable greetd
  ansible.builtin.service:
    name: greetd
    enabled: true
    state: started
  tags:
    - molecule-idempotence-notest
