---

- name: Configure pacman mirrorlist
  ansible.builtin.template:
    src: etc/pacman.d/mirrorlist.j2
    dest: /etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: 0644

- name: Install baseline packages
  ansible.builtin.package:
    name: '{{ os_baseline_packages }}'
    state: present

- name: Configure global environment variables
  ansible.builtin.template:
    src: etc/environment.j2
    dest: /etc/environment
    owner: root
    group: root
    mode: 0644

- name: Read current hwclock timezone settings
  ansible.builtin.command:
    timedatectl show -p LocalRTC --value
  register: os_baseline_register_hwclock
  changed_when: false

- name: Configure hwclock timezone settings
  ansible.builtin.command:
    timedatectl set-local-rtc '{{ os_baseline_timezone_hwclock }}'
  changed_when: true
  when: (os_baseline_register_hwclock.stdout == 'no' and os_baseline_timezone_hwclock) or
        (os_baseline_register_hwclock.stdout == 'yes' and not os_baseline_timezone_hwclock)

- name: Configure system timezone
  ansible.builtin.file:
    path: /etc/localtime
    src: '../usr/share/zoneinfo/{{ os_baseline_timezone }}'
    owner: root
    group: root
    state: link

- name: Configure systemd-timesyncd
  ansible.builtin.template:
    src: etc/systemd/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart systemd-timesyncd

# timesyncd does not like to be run in a container
# (`ConditionVirtualization=!container`) thus we need to skip this
# task during the molecule idempotence test
- name: Enable systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    enabled: true
    state: started
  tags:
    - molecule-idempotence-notest

- name: Activate and generate locales
  ansible.builtin.replace:
    path: /etc/locale.gen
    regexp: '#{{ item }}'
    replace: '{{ item }}'
    owner: root
    group: root
    mode: 0644
  loop: '{{ os_baseline_locales }}'
  notify: Generate locales

- name: Configure systemd-wide locales
  ansible.builtin.template:
    src: etc/locale.conf.j2
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: 0644

- name: Configure vconsole settings
  ansible.builtin.template:
    src: etc/vconsole.conf.j2
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: 0644

# Configuring the hostname does not work well in container-based molecule runs
- name: Configure system hostname
  ansible.builtin.template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags:
    - molecule-notest
