---

- name: read current hwclock timezone settings
  ansible.builtin.command:
    timedatectl show -p LocalRTC --value
  register: os_baseline_register_hwclock
  changed_when: false

- name: configure hwclock timezone settings
  ansible.builtin.command:
    timedatectl set-local-rtc '{{ os_baseline_timezone_hwclock }}'
  when: (os_baseline_register_hwclock.stdout == 'no' and os_baseline_timezone_hwclock) or
        (os_baseline_register_hwclock.stdout == 'yes' and not os_baseline_timezone_hwclock)

- name: configure system timezone
  ansible.builtin.file:
    path: /etc/localtime
    src: '../usr/share/zoneinfo/{{ os_baseline_timezone }}'
    owner: root
    group: root
    state: link

- name: configure systemd-timesyncd
  ansible.builtin.template:
    src: etc/systemd/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-timesyncd

# timesyncd does not like to be ran in a container
# (`ConditionVirtualization=!container`) thus we need to skip this
# task during the molecule idempotence test
- name: activate systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    enabled: yes
    state: started
  tags:
    - molecule-idempotence-notest

- name: activate and generate locales
  ansible.builtin.replace:
    path: /etc/locale.gen
    regexp: '#{{ item }}'
    replace: '{{ item }}'
    owner: root
    group: root
    mode: 0644
  loop: '{{ os_baseline_locales }}'
  notify: generate locales

- name: configure pacman mirrorlist
  ansible.builtin.template:
    src: etc/pacman.d/mirrorlist.j2
    dest: /etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: 0644

- name: install baseline packages
  ansible.builtin.package:
    name: '{{ os_baseline_packages }}'
    state: present
