---

- name: Converge
  hosts: all
  gather_facts: true

  tasks:
    - name: Include role wayfire
      ansible.builtin.include_role:
        name: karras.linux_client.wayfire
      vars:
        wayfire_greetd_config: |
          [autostart]
          autostart_wf_shell = false
          dm = gtkgreet -l -s /etc/greetd/gtkgreet.css && wayland-logout

          [core]
          plugins  = autostart
          vheight  = 1
          vwidth   = 1
          xwayland = false
        wayfire_run_wrapper: |
          export XDG_CONFIG_HOME="$HOME/.local/etc"
          export XDG_CACHE_HOME="$HOME/.local/var/cache"
          export XDG_DATA_HOME="$HOME/.local/share"
          export XDG_STATE_HOME="$HOME/.local/var/lib"

          systemctl --user set-environment XDG_CONFIG_HOME="$HOME/.local/etc"
          systemctl --user set-environment WAYLAND_DISPLAY=wayland-1
          systemctl --user set-environment WAYFIRE_SOCKET=/tmp/wayfire-wayland-1.socket

          systemctl --user set-environment $(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)
          export $(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)

          wayfire
