---

- name: Converge
  hosts: all
  gather_facts: yes

  roles:
    - role: wayfire
      wayfire_greetd_config: |
        [autostart]
        autostart_wf_shell = false
        dm = gtkgreet -l -s /etc/greetd/gtkgreet.css && wayland-logout

        [core]
        plugins  = autostart
        vheight  = 1
        vwidth   = 1
        xwayland = false
