---

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Check if wayfire was successfully installed
      ansible.builtin.command:
        wayfire -v
      register: out
      changed_when: false
      failed_when: out.rc != 0
