---

argument_specs:
  main:
    short_description: Manages Wayfire related settings.
    options:
      wayfire_dependencies:
        description:
          - List of additional packages to install
        type: list
        elements: str
        required: no
        default:
          - polkit
      wayfire_greetd_config:
        description:
          - Optional greetd integration to configure (multiline string).
        type: str
        required: no
        default: ''
      wayfire_packages:
        description:
          - List of Wayfire related packages to install including their
            version.
        type: list
        elements: dict
        required: no
        default:
          - name: wf-config
            version: 0.7.1-3
            url: 'https://github.com/karras/aur-package-builds/releases/download/v1.0.1'
            suffix: -x86_64.pkg.tar.zst
          - name: wayfire
            version: 0.7.2-1
            url: 'https://github.com/karras/aur-package-builds/releases/download/v1.0.1'
            suffix: -x86_64.pkg.tar.zst
        options:
          name:
            description:
              - Name of the package to install.
            type: str
            required: yes
          version:
            description:
              - Version of the package to install.
            type: str
            required: yes
          url:
            description:
              - Base URL from where the package is downloaded.
            type: str
            required: yes
          suffix:
            description:
              - Suffix of the package name.
            type: str
            required: yes
