---

argument_specs:
  main:
    short_description: Installs and configures the Wayfire compositor.
    options:
      wayfire_greetd_config:
        description:
          - Optional greetd integration config to deploy (multiline string).
          - This allows running a greetd-gtkgreet session via Wayfire, which in
            turn spawns a proper Wayfire session after login.
        type: str
        required: false
        default: ''
      wayfire_packages:
        description:
          - List of Wayfire related packages to install.
        type: list
        elements: str
        required: false
        default:
          - polkit
          - wf-config
          - wayfire
      wayfire_repositories:
        description:
          - List of Pacman repositories to configure.
        type: list
        elements: dict
        required: false
        default:
          - name: karras
            server: https://github.com/karras/aur-package-builds/releases/download/v2.1.0
            key: https://raw.githubusercontent.com/karras/aur-package-builds/main/builder_public_key.asc
            key_id: 25267573FD638312C5EBE4C40C758F9503EDE7AF
        options:
          name:
            description:
              - Name of the repository.
            type: str
            required: true
          server:
            description:
              - Server URL of the repository.
            type: str
            required: true
          key:
            description:
              - GPG key URL of the repository.
            type: str
            required: true
          key_id:
            description:
              - GPG key ID of the repository.
            type: str
            required: true
      wayfire_run_wrapper:
        description:
          - Optional wrapper script to deploy (multiline string).
          - It can be desired to run Wayfire via wrapper script, which takes
            care of setting additional environment vars first (e.g. `XDG`)
            before starting Wayfire.
        type: str
        required: false
        default: ''
