---

- name: Verify
  hosts: all
  gather_facts: no

  tasks:
  - name: check if bemenu was successfully installed
    ansible.builtin.command:
      bemenu -v
    register: out
    changed_when: no
    failed_when:
      - out.rc != 0

  - name: check if light was successfully installed
    ansible.builtin.command:
      light -V
    register: out
    changed_when: no
    failed_when:
      - out.rc != 0

  - name: check if neovim was successfully installed
    ansible.builtin.command:
      nvim -v
    register: out
    changed_when: no
    failed_when:
      - out.rc != 0

  - name: check if swaybg was successfully installed
    ansible.builtin.command:
      swaybg -v
    register: out
    changed_when: no
    failed_when:
      - out.rc != 0

  - name: check if swayidle was successfully installed
    ansible.builtin.command:
      swayidle -h
    register: out
    changed_when: no
    failed_when:
      - out.rc != 255

  - name: check if swaylock was successfully installed
    ansible.builtin.command:
      swaylock -v
    register: out
    changed_when: no
    failed_when:
      - out.rc != 0

  # Terminator requires a GUI environment to print its version or help message
  # thus we assume it is okay if it fails, there should be a better way to fix
  # out though
  - name: check if terminator was successfully installed
    ansible.builtin.command:
      terminator -v
    register: out
    changed_when: no
    failed_when:
      - out.rc != 1

  - name: check if waybar was successfully installed
    ansible.builtin.command:
      waybar -v
    register: out
    changed_when: no
    failed_when:
      - out.rc != 0
