---

argument_specs:
  main:
    short_description: Manages NetworkManager related settings.
    options:
      networkmanager_packages:
        description:
          - List of networkmanager related packages to install.
        type: list
        elements: str
        required: no
        default:
          - networkmanager
          - network-manager-applet
          - nm-connection-editor
      networkmanager_service_activation:
        description:
          - List of networkmanager related services to activate.
        type: list
        elements: str
        required: no
        default:
          - NetworkManager
