---

- name: Reboot system
  ansible.builtin.reboot:
  when: ansible_connection not in ["container", "docker", "community.docker.docker"]

- name: Reload daemons
  ansible.builtin.systemd:
    daemon_reload: true
