---

# List of removable media partitions (1.1.18 - 1.1.20)
cis_baseline_removable_media_partitions:
  - /mnt/cdrom
  - /mnt/floppy

# List of gpg key packages to install (1.2.2)
cis_baseline_gpg_key_packages:
  - archlinux-keyring
