---

- name: Restart systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: Generate locales
  ansible.builtin.command:
    locale-gen
  changed_when: true
