---

- name: install networkmanager packages
  ansible.builtin.package:
    name: '{{ networkmanager_packages }}'
    state: present

# Service related tasks do not work well in molecule idempotence tests
- name: enable networkmanager
  ansible.builtin.service:
    name: NetworkManager
    enabled: yes
    state: started
  tags:
    - molecule-idempotence-notest
