---

# 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
- name: 1.1.1.1 disable cramfs filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_cramfs.conf.j2
    dest: /etc/modprobe.d/cis_cramfs.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.1' in cis_generic_linux_ignored_rules

# 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
- name: 1.1.1.1 remove loaded cramfs filesystem module
  ansible.builtin.command:
    modprobe -r cramfs
  changed_when: no
  failed_when: no
  when: not '1.1.1.1' in cis_generic_linux_ignored_rules

# 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled (Scored)
- name: 1.1.1.2 disable freevxfs filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_freevxfs.conf.j2
    dest: /etc/modprobe.d/cis_freevxfs.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.2' in cis_generic_linux_ignored_rules

# 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled (Scored)
- name: 1.1.1.2 remove loaded freevxfs filesystem module
  ansible.builtin.command:
    modprobe -r freevxfs
  changed_when: no
  failed_when: no
  when: not '1.1.1.2' in cis_generic_linux_ignored_rules

# 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled (Scored)
- name: 1.1.1.3 disable jffs2 filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_jffs2.conf.j2
    dest: /etc/modprobe.d/cis_jffs2.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.3' in cis_generic_linux_ignored_rules

# 1.1.1.3 Ensure mounting of freevxfs filesystems is disabled (Scored)
- name: 1.1.1.3 remove loaded jffs2 filesystem module
  ansible.builtin.command:
    modprobe -r jffs2
  changed_when: no
  failed_when: no
  when: not '1.1.1.3' in cis_generic_linux_ignored_rules

# 1.1.1.4 Ensure mounting of hfs filesystems is disabled (Scored)
- name: 1.1.1.4 disable hfs filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_hfs.conf.j2
    dest: /etc/modprobe.d/cis_hfs.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.4' in cis_generic_linux_ignored_rules

# 1.1.1.4 Ensure mounting of hfs filesystems is disabled (Scored)
- name: 1.1.1.4 remove loaded hfs filesystem module
  ansible.builtin.command:
    modprobe -r hfs
  changed_when: no
  failed_when: no
  when: not '1.1.1.4' in cis_generic_linux_ignored_rules

# 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled (Scored)
- name: 1.1.1.5 disable hfsplus filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_hfsplus.conf.j2
    dest: /etc/modprobe.d/cis_hfsplus.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.5' in cis_generic_linux_ignored_rules

# 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled (Scored)
- name: 1.1.1.5 remove loaded hfsplus filesystem module
  ansible.builtin.command:
    modprobe -r hfsplus
  changed_when: no
  failed_when: no
  when: not '1.1.1.5' in cis_generic_linux_ignored_rules

# 1.1.1.6 Ensure mounting of squashfs filesystems is disabled (Scored)
- name: 1.1.1.6 disable squashfs filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_squashfs.conf.j2
    dest: /etc/modprobe.d/cis_squashfs.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.6' in cis_generic_linux_ignored_rules

# 1.1.1.6 Ensure mounting of squashfs filesystems is disabled (Scored)
- name: 1.1.1.6 remove loaded squashfs filesystem module
  ansible.builtin.command:
    modprobe -r squashfs
  changed_when: no
  failed_when: no
  when: not '1.1.1.6' in cis_generic_linux_ignored_rules

# 1.1.1.7 Ensure mounting of udf filesystems is disabled (Scored)
- name: 1.1.1.7 disable udf filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_udf.conf.j2
    dest: /etc/modprobe.d/cis_udf.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.7' in cis_generic_linux_ignored_rules

# 1.1.1.7 Ensure mounting of udf filesystems is disabled (Scored)
- name: 1.1.1.7 remove loaded udf filesystem module
  ansible.builtin.command:
    modprobe -r udf
  changed_when: no
  failed_when: no
  when: not '1.1.1.7' in cis_generic_linux_ignored_rules

# 1.1.1.8 Ensure mounting of vfat filesystems is disabled (Scored)
- name: 1.1.1.8 disable vfat filesystem module
  ansible.builtin.template:
    src: etc/modprobe.d/cis_vfat.conf.j2
    dest: /etc/modprobe.d/cis_vfat.conf
    owner: root
    group: root
    mode: 0644
  when: not '1.1.1.8' in cis_generic_linux_ignored_rules

# 1.1.1.8 Ensure mounting of vfat filesystems is disabled (Scored)
- name: 1.1.1.8 remove loaded vfat filesystem module
  ansible.builtin.command:
    modprobe -r vfat
  changed_when: no
  failed_when: no
  when: not '1.1.1.8' in cis_generic_linux_ignored_rules
