---

name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build collection
        run: |
          ansible-galaxy collection build

      - name: Publish collection
        run: |
          ansible-galaxy collection publish *.tar.gz --token=${{ secrets.GALAXY_API_KEY }}
