---

name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Lint with ansible-lint including yamllint
        run: |
          ansible-lint

      - name: Test with molecule
        run: |
          cd ./roles/desktop_baseline && molecule test
          cd ../firewalld && molecule test
          cd ../greetd && molecule test
          cd ../hardware && molecule test
          cd ../networkmanager && molecule test
          cd ../os_baseline && molecule test
          cd ../users && molecule test
          cd ../wayfire && molecule test
